# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/summer_homework/Lab_10/Lab_10.srcs/sources_1/ip/game_R_Rom/game_R_Rom.xci
# IP: The module: 'game_R_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/summer_homework/Lab_10/Lab_10.srcs/sources_1/ip/game_R_Rom/game_R_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_R_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/summer_homework/Lab_10/Lab_10.srcs/sources_1/ip/game_R_Rom/game_R_Rom.xci
# IP: The module: 'game_R_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/summer_homework/Lab_10/Lab_10.srcs/sources_1/ip/game_R_Rom/game_R_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_R_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
